import {
  HomeIcon,
  ClipboardDocumentListIcon,
  TagIcon,
  ArrowLeftEndOnRectangleIcon,
  Cog6ToothIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  CreditCardIcon,
  Bars3Icon,
  XMarkIcon,
  PlusIcon,
  ScaleIcon,
  AdjustmentsHorizontalIcon,
  FunnelIcon,
  PencilSquareIcon,
  PencilIcon,
  BanknotesIcon,
} from '@heroicons/vue/20/solid'

import {
  PencilSquareIcon as PencilSquareIconOutline,
  TrashIcon as TrashIconOutline,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconOutline,
  FunnelIcon as FunnelIconOutline,
  ArrowUpTrayIcon as ArrowUpTrayIconOutline,
  BanknotesIcon as BanknotesIconOutline,
} from '@heroicons/vue/24/outline'

const Icon = {
  HomeIcon,
  ClipboardDocumentListIcon,
  TagIcon,
  ArrowLeftEndOnRectangleIcon,
  Cog6ToothIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  CreditCardIcon,
  Bars3Icon,
  XMarkIcon,
  PlusIcon,
  ScaleIcon,
  PencilSquareIcon,
  PencilSquareIconOutline,
  TrashIconOutline,
  AdjustmentsHorizontalIcon,
  FunnelIcon,
  AdjustmentsHorizontalIconOutline,
  FunnelIconOutline,
  ArrowUpTrayIconOutline,
  PencilIcon,
  BanknotesIcon,
  BanknotesIconOutline,
}

export default Icon
